name: App Linter Check

on:
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint:all
      - name: Run Test
        run: npm run test:ci
